"""add unified research cache

Revision ID: 0fa4c41e1adc
Revises: 9e007a642807
Create Date: 2026-03-04 20:46:19.032195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa4c41e1adc'
down_revision: Union[str, Sequence[str], None] = '9e007a642807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('SEC', 'NEWS', 'SOCIAL', 'X', name='researchsourcetype'), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sentiment_reason', sa.Text(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_cache_expire_at'), 'research_cache', ['expire_at'], unique=False)
    op.create_index(op.f('ix_research_cache_id'), 'research_cache', ['id'], unique=False)
    op.create_index(op.f('ix_research_cache_key'), 'research_cache', ['key'], unique=True)
    op.create_index(op.f('ix_research_cache_source_type'), 'research_cache', ['source_type'], unique=False)
    op.create_index(op.f('ix_research_cache_ticker'), 'research_cache', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_cache_ticker'), table_name='research_cache')
    op.drop_index(op.f('ix_research_cache_source_type'), table_name='research_cache')
    op.drop_index(op.f('ix_research_cache_key'), table_name='research_cache')
    op.drop_index(op.f('ix_research_cache_id'), table_name='research_cache')
    op.drop_index(op.f('ix_research_cache_expire_at'), table_name='research_cache')
    op.drop_table('research_cache')
    # ### end Alembic commands ###
