"""Make assets global

Revision ID: 80ae3fa232bd
Revises: 93d3b2fb0b1f
Create Date: 2026-03-02 23:55:08.742826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ae3fa232bd'
down_revision: Union[str, Sequence[str], None] = '93d3b2fb0b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.drop_column('assets', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.alter_column('assets', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
