"""add sec cache table

Revision ID: 9e007a642807
Revises: 2d03554b58bf
Create Date: 2026-03-04 19:54:33.732998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e007a642807'
down_revision: Union[str, Sequence[str], None] = '2d03554b58bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sec_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('accession_number', sa.String(), nullable=False),
    sa.Column('filing_type', sa.String(), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sec_cache_accession_number'), 'sec_cache', ['accession_number'], unique=False)
    op.create_index(op.f('ix_sec_cache_filing_date'), 'sec_cache', ['filing_date'], unique=False)
    op.create_index(op.f('ix_sec_cache_filing_type'), 'sec_cache', ['filing_type'], unique=False)
    op.create_index(op.f('ix_sec_cache_id'), 'sec_cache', ['id'], unique=False)
    op.create_index(op.f('ix_sec_cache_section_name'), 'sec_cache', ['section_name'], unique=False)
    op.create_index(op.f('ix_sec_cache_ticker'), 'sec_cache', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sec_cache_ticker'), table_name='sec_cache')
    op.drop_index(op.f('ix_sec_cache_section_name'), table_name='sec_cache')
    op.drop_index(op.f('ix_sec_cache_id'), table_name='sec_cache')
    op.drop_index(op.f('ix_sec_cache_filing_type'), table_name='sec_cache')
    op.drop_index(op.f('ix_sec_cache_filing_date'), table_name='sec_cache')
    op.drop_index(op.f('ix_sec_cache_accession_number'), table_name='sec_cache')
    op.drop_table('sec_cache')
    # ### end Alembic commands ###
