"""drop legacy cache tables

Revision ID: 9e6a98c19bf1
Revises: 0fa4c41e1adc
Create Date: 2026-03-04 23:49:30.894697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e6a98c19bf1'
down_revision: Union[str, Sequence[str], None] = '0fa4c41e1adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_cache_url'), table_name='news_cache')
    op.drop_table('news_cache')
    op.drop_index(op.f('ix_sec_cache_accession_number'), table_name='sec_cache')
    op.drop_index(op.f('ix_sec_cache_filing_date'), table_name='sec_cache')
    op.drop_index(op.f('ix_sec_cache_filing_type'), table_name='sec_cache')
    op.drop_index(op.f('ix_sec_cache_id'), table_name='sec_cache')
    op.drop_index(op.f('ix_sec_cache_section_name'), table_name='sec_cache')
    op.drop_index(op.f('ix_sec_cache_ticker'), table_name='sec_cache')
    op.drop_table('sec_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sec_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accession_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filing_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filing_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('section_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sec_cache_pkey'))
    )
    op.create_index(op.f('ix_sec_cache_ticker'), 'sec_cache', ['ticker'], unique=False)
    op.create_index(op.f('ix_sec_cache_section_name'), 'sec_cache', ['section_name'], unique=False)
    op.create_index(op.f('ix_sec_cache_id'), 'sec_cache', ['id'], unique=False)
    op.create_index(op.f('ix_sec_cache_filing_type'), 'sec_cache', ['filing_type'], unique=False)
    op.create_index(op.f('ix_sec_cache_filing_date'), 'sec_cache', ['filing_date'], unique=False)
    op.create_index(op.f('ix_sec_cache_accession_number'), 'sec_cache', ['accession_number'], unique=False)
    op.create_table('news_cache',
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expire_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('url', name=op.f('news_cache_pkey'))
    )
    op.create_index(op.f('ix_news_cache_url'), 'news_cache', ['url'], unique=False)
    # ### end Alembic commands ###
