"""evolve_report_model_fts

Revision ID: e20db4ae0573
Revises: bc7aa1c87155
Create Date: 2026-03-02 00:30:54.087387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e20db4ae0573'
down_revision: Union[str, Sequence[str], None] = 'bc7aa1c87155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the reportcategory enum type
    report_category_enum = postgresql.ENUM('STOCK', 'REAL_ESTATE', 'MACRO', 'FUND', 'GENERAL', name='reportcategory')
    report_category_enum.create(op.get_bind())

    op.add_column('reports', sa.Column('title', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('topic', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('category', sa.Enum('STOCK', 'REAL_ESTATE', 'MACRO', 'FUND', 'GENERAL', name='reportcategory'), nullable=False))
    op.add_column('reports', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(topic, '') || ' ' || coalesce(content, ''))", persisted=True), nullable=True))
    op.create_index('ix_report_search_vector', 'reports', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_reports_topic'), 'reports', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_topic'), table_name='reports')
    op.drop_index('ix_report_search_vector', table_name='reports', postgresql_using='gin')
    op.drop_column('reports', 'search_vector')
    op.drop_column('reports', 'tags')
    op.drop_column('reports', 'category')
    op.drop_column('reports', 'topic')
    op.drop_column('reports', 'title')

    # Drop the reportcategory enum type
    report_category_enum = postgresql.ENUM('STOCK', 'REAL_ESTATE', 'MACRO', 'FUND', 'GENERAL', name='reportcategory')
    report_category_enum.drop(op.get_bind())
    # ### end Alembic commands ###
